apps/first_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'first_app'

urlpatterns = [
    url(r'^$',views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$',views.logout, name = 'logout'),
]

apps/newsfeed/urls.py
from django.conf.urls import url

from . import views

app_name = 'newsfeed'
urlpatterns = [
    url(r'^addpost$', views.addPost, name = 'addPost'),
    url(r'^success$',views.success, name = 'success'),
    url(r'^(?P<id>\d+)/add_like$',views.addLike, name = 'addLike'),
    url(r'^(?P<id>\d+)/delete_post$',views.deletePost, name = 'deletePost'),
    url(r'^(?P<id>\d+)/edit_post$',views.editPost, name = 'editPost'),
    url(r'^update_post/(?P<id>\d+)$',views.updatePost, name = 'updatePost'),
]
    

demo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^',include("apps.first_app.urls", namespace = 'loginreg')),
    url(r'^newsfeed/', include("apps.newsfeed.urls",namespace = 'newsfeed')),
    
]

apps/first_app/models.py
from django.db import models

import re, bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.

class UserManager(models.Manager):
    def register(self,request_object):
        errors = []

        if len(request_object['firstname']) < 2:
            errors.append('First name must be at least 2 characters long')
        
        if len(request_object['lastname']) < 2:
            errors.append('Last name must be at least 2 characters long')

        if not len(request_object['email']):
            errors.append("Email is required")
        else:
            if not EMAIL_REGEX.match(request_object['email']):
                errors.append("Enter a valid email")
        
        if len(request_object['password']) < 8:
            errors.append("Password must be at least 8 characters long")
        
        if not request_object['password'] == request_object['confirm_password']:
            errors.append("Confirm Password doesn't match Password")
        
        if self.filter(email = request_object['email']):
            errors.append("This email already belongs to a user")

        response_to_views = {}

        if len(errors) == 0:
            user = self.create(firstname = request_object['firstname'], lastname = request_object['lastname'],email = request_object['email'],password = request_object['password'])
            response_to_views['user'] =  user
            response_to_views['status'] = True
        else:
            response_to_views['errors'] = errors
            response_to_views['status'] = False
        
        return response_to_views

    def login(self,request_object):
        user = self.filter(email = request_object['email'])
        response_to_views = {}

        if not user:
            response_to_views['status'] = False
            response_to_views['errors'] = 'Email address not found'
        else:
            
            if user[0].password == request_object['password']:
                response_to_views['status'] = True
                response_to_views['user'] = user.first()

            else:
                response_to_views['status'] = False
                response_to_views['errors'] = 'Invalid Email/password combination'

        return response_to_views


class User(models.Model):
    firstname = models.CharField(max_length = 45)
    lastname = models.CharField(max_length = 45)
    email = models.CharField(max_length = 50)
    password = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

apps/newsfeed/models.py
from django.db import models

from ..first_app.models import User

# Create your models here.

class PostManager(models.Manager):
    def validate_post(self,request_object,user_id):
        status = False
        
        if len(request_object['post']) > 180:
            status = False
        else:
            user = User.objects.get(id = user_id)

            new_post = self.create(post = request_object['post'], user = user)

            status = True
        
        return status

    def validate_like(self, user_id, post_id):
        user = User.objects.get(id = user_id)

        post = Post.objects.get(id = post_id)

        if not user in post.likes.all():
            post.likes.add(user)

        return 

class Post(models.Model): 
    post = models.CharField(max_length = 180)
    user = models.ForeignKey(User, related_name = "created_by", on_delete = models.DO_NOTHING) 
    likes = models.ManyToManyField(User, related_name = "likes")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = PostManager()

apps/first_app/views.py
from django.shortcuts import render,redirect

from django.contrib import messages

from .models import User

# Create your views here.

def index(request):
    return render(request,"first_app/index.html")


def register(request):
    if request.method == 'POST':
        response_from_models = User.objects.register(request.POST)

        if response_from_models['status'] == True:
            request.session['user_id'] = response_from_models['user'].id
            return redirect("newsfeed:success")
        else:
            for error in response_from_models['errors']:
                messages.error(request,error)
                return redirect('loginreg:index')

def login(request):
    if request.method == 'POST':
        response_from_models = User.objects.login(request.POST)

        if response_from_models['status']:
            request.session['user_id'] = response_from_models['user'].id

            return redirect("newsfeed:success")
        else:
            messages.error(request, response_from_models['errors'])
            return redirect('loginreg:index')

def logout(request):
    request.session.clear()
    return redirect('loginreg:index')

apps/newsfeed/views.py
from django.shortcuts import render,redirect

from django.contrib import messages

from ..first_app.models import User

from . models import Post

# Create your views here.
def success(request):
    if 'user_id' in request.session:
        context = {
            'user' : User.objects.get(id = request.session['user_id']),
            'posts': Post.objects.all().order_by(
                '-created_at')
        }
    
        return render(request,"newsfeed/newsfeed.html",context)

    return redirect('loginreg:index')


def addPost(request):
    response_from_models = Post.objects.validate_post(request.POST,request.session['user_id'])

    if response_from_models == False:
        messages.error(request,"Your post must be 180 characters")
        
    return redirect('newsfeed:success')


def addLike(request,id):
    post_id = id 

    Post.objects.validate_like(request.session['user_id'], post_id)

    return redirect("newsfeed:success")


def deletePost(request,id):
    Post.objects.get(id = id).delete()  

    return redirect("newsfeed:success")

def editPost(request,id):
    post = Post.objects.get(id = id)
    context = {
        'post': post
    }

    return render(request,"newsfeed/editpost.html",context)


def updatePost(request,id):
    if request.method == 'POST':
        post = Post.objects.get(id = id)

        post.post = request.POST['post']

        post.save()

        return redirect('newsfeed:success')

    route = str(id) + "/edit_post"

    return redirect("newsfeed:editPost")

apps/first_app/templates/first_app/index.html
<html>
    <body>
        <style>
            input{
                display:block;
            }
        </style>


        {% if messages %}
            {% for message in messages %}
                <p style="color:red">{{message.message}}</p>
            {% endfor %}
        {% endif %}

        <h2>Register</h2>

        <form action = "{% url 'loginreg:register' %} " method = "POST">
            {% csrf_token %}
            <label>Firstname</label>
            <input type = "text" name = "firstname">

            <label>Lastname</label>
            <input type = "text" name = "lastname">

            <label>Email</label>
            <input type = "text" name = "email">

            <label>Password</label>
            <input type = "password" name = "password">

            <label>Confirm Password</label>
            <input type = "password" name = "confirm_password">

            <input type="submit" value = "Register!">
        </form>

        <h2>Login</h2>

        <form action = "{% url 'loginreg:login' %} " method = "POST">
            {% csrf_token %}
            <label>Email</label>
            <input type = "text" name = "email">

            <label>Password</label>
            <input type = "password" name = "password">

            <input type="submit" value = "Login!">
        </form>
    </body>
</html>

apps/newsfeed/templates/newsfeed/editpost.html
<html>
    <head>
        <title>Edit Post</title>
        <style>
             input{
                display:block;
            }
        </style>
    </head>
    
    <body>
        <h3>Edit your post</h3>
        <form action = "{% url 'newsfeed:updatePost' id=post.id %} "  method = "POST">
            {% csrf_token %}

            <textarea rows = 15 cols = 200 name = "post">{{post.post}}</textarea>

            <input type = "submit" value = "Submit Post!">
        </form>
        {% if messages %}
            {% for message in messages %}
                <p style="color:red">{{message.message}}</p>
            {% endfor %}
        {% endif %}
    </body>
</html>

apps/newsfeed/templates/newsfeed/newsfeed.html
<html>
    <head>
        <title>Welcome to News Feed</title>

        <style>
            input{
                display:block;
            }

            div{
                border: 2px solid black
            }
        </style>

    </head>

    <h3>Welcome {{user.firstname}}</h3>


    <h3>Add your post</h3>
    <form action = "{% url 'newsfeed:addPost' %} "  method = "POST">
        {% csrf_token %}
        <textarea rows = 15 cols = 200 name = "post"></textarea>

        <input type = "submit" value = "Submit Post!">
    </form>
    {% if messages %}
        {% for message in messages %}
            <p style="color:red">{{message.message}}</p>
        {% endfor %}
    {% endif %}

    
    {% for post in posts %}
        <div>
            <p>{{post.user.firstname}} {{post.user.lastname}} says:</p>
            <p>{{post.post}}</p>
            <p>{{post.created_at}}</p>
            <a href = "{% url 'newsfeed:addLike' id=post.id %}" ><button>Like</button>{{post.likes.all.count}}</a>
            {% if request.session.user_id == post.user.id %}
                <a href = "{% url 'newsfeed:deletePost' id=post.id %} "><button>Delete</button></a>  
                <a href = "{% url 'newsfeed:editPost' id=post.id %} "><button>Edit</button></a>
            {% endif %} 
        </div>
    {% endfor %}

    <a href = "{% url 'loginreg:logout'%} "><button>Logout</button></a>
</html>